import Foundation
import Testing
@testable import BookmarkPrimitive

@MainActor
@Suite("BookmarkStore Tests")
struct BookmarkStoreTests {
    @Test func addAndRetrieve() {
        let store = BookmarkStore()
        let bookmark = Bookmark(name: "Chapter 1", anchor: BookmarkAnchor(contentID: "block-1"))
        store.add(bookmark)
        #expect(store.bookmarks.count == 1)
        #expect(store.bookmark(named: "Chapter 1") != nil)
    }

    @Test func removeBookmark() {
        let store = BookmarkStore()
        let bookmark = Bookmark(name: "Chapter 1", anchor: BookmarkAnchor(contentID: "block-1"))
        store.add(bookmark)
        store.remove(bookmark.id)
        #expect(store.bookmarks.isEmpty)
    }

    @Test func updateBookmarkName() {
        let store = BookmarkStore()
        let bookmark = Bookmark(name: "Chapter 1", anchor: BookmarkAnchor(contentID: "block-1"))
        store.add(bookmark)
        store.update(bookmark.id, name: "Introduction")
        #expect(store.bookmark(for: bookmark.id)?.name == "Introduction")
    }

    @Test func findByContentID() {
        let store = BookmarkStore()
        let bookmark = Bookmark(name: "Heading", anchor: BookmarkAnchor(contentID: "block-42"))
        store.add(bookmark)
        #expect(store.bookmark(forContentID: "block-42") != nil)
        #expect(store.bookmark(forContentID: "block-99") == nil)
    }

    @Test func autoVsManualFilters() {
        let store = BookmarkStore()
        store.add(Bookmark(name: "Auto", anchor: BookmarkAnchor(contentID: "b1"), isAutoGenerated: true))
        store.add(Bookmark(name: "Manual", anchor: BookmarkAnchor(contentID: "b2"), isAutoGenerated: false))
        #expect(store.autoBookmarks.count == 1)
        #expect(store.manualBookmarks.count == 1)
    }

    @Test func regenerateReplacesAutoBookmarks() {
        let store = BookmarkStore()
        store.add(Bookmark(name: "Old Auto", anchor: BookmarkAnchor(contentID: "b1"), isAutoGenerated: true))
        store.add(Bookmark(name: "Manual", anchor: BookmarkAnchor(contentID: "b2"), isAutoGenerated: false))
        store.regenerate(from: [
            (name: "New Heading", contentID: "b3", metadata: ["level": "1"]),
        ])
        #expect(store.autoBookmarks.count == 1)
        #expect(store.autoBookmarks[0].name == "New Heading")
        #expect(store.manualBookmarks.count == 1)
    }

    @Test func resolveTitleReference() {
        let store = BookmarkStore()
        let bookmark = Bookmark(id: "intro", name: "Introduction", anchor: BookmarkAnchor(contentID: "b1"))
        store.add(bookmark)
        let ref = CrossReference(targetBookmarkID: "intro", displayStyle: .title)
        let resolved = store.resolve(ref)
        #expect(resolved.isValid == true)
        #expect(resolved.displayText == "Introduction")
    }

    @Test func resolveNumberAndTitle() {
        let store = BookmarkStore()
        let bookmark = Bookmark(
            id: "ch1",
            name: "Getting Started",
            anchor: BookmarkAnchor(contentID: "b1"),
            metadata: ["number": "1.2"]
        )
        store.add(bookmark)
        let ref = CrossReference(targetBookmarkID: "ch1", displayStyle: .numberAndTitle)
        let resolved = store.resolve(ref)
        #expect(resolved.displayText == "1.2 Getting Started")
    }

    @Test func resolveBrokenReference() {
        let store = BookmarkStore()
        let ref = CrossReference(targetBookmarkID: "nonexistent", displayStyle: .title)
        let resolved = store.resolve(ref)
        #expect(resolved.isValid == false)
        #expect(resolved.displayText == "[broken reference]")
    }

    @Test func observerNotifiedOnAdd() {
        let store = BookmarkStore()
        var received: BookmarkMutation?
        _ = store.addObserver { mutation in received = mutation }
        let bookmark = Bookmark(name: "Test", anchor: BookmarkAnchor(contentID: "b1"))
        store.add(bookmark)

        if case .added(let id) = received {
            #expect(id == bookmark.id)
        } else {
            #expect(Bool(false), "Expected .added mutation")
        }
    }
}
