import Foundation
import Testing
@testable import BookmarkPrimitive

@Suite("BookmarkPrimitive Model Tests")
struct ModelTests {
    @Test func bookmarkIDExpressibleByStringLiteral() {
        let id: BookmarkID = "intro"
        #expect(id.rawValue == "intro")
    }

    @Test func bookmarkCodableRoundTrip() throws {
        let bookmark = Bookmark(
            name: "Introduction",
            anchor: BookmarkAnchor(contentID: "block-1", offset: 0),
            isAutoGenerated: true,
            metadata: ["level": "1"]
        )
        let data = try JSONEncoder().encode(bookmark)
        let decoded = try JSONDecoder().decode(Bookmark.self, from: data)
        #expect(decoded.name == "Introduction")
        #expect(decoded.isAutoGenerated == true)
        #expect(decoded.metadata["level"] == "1")
    }

    @Test func crossReferenceCodableRoundTrip() throws {
        let ref = CrossReference(targetBookmarkID: "intro", displayStyle: .numberAndTitle)
        let data = try JSONEncoder().encode(ref)
        let decoded = try JSONDecoder().decode(CrossReference.self, from: data)
        #expect(decoded == ref)
    }

    @Test func crossReferenceStyles() {
        #expect(CrossReferenceStyle.pageNumber.rawValue == "pageNumber")
        #expect(CrossReferenceStyle.title.rawValue == "title")
        #expect(CrossReferenceStyle.aboveBelow.rawValue == "aboveBelow")
    }
}
