import Foundation

public struct BookmarkID: RawRepresentable, Hashable, Codable, Sendable, ExpressibleByStringLiteral {
    public let rawValue: String

    public init(rawValue: String) {
        self.rawValue = rawValue
    }

    public init(stringLiteral value: String) {
        self.rawValue = value
    }

    public init() {
        self.rawValue = UUID().uuidString
    }
}

public struct BookmarkAnchor: Codable, Sendable, Equatable {
    public var contentID: String
    public var offset: Int?

    public init(contentID: String, offset: Int? = nil) {
        self.contentID = contentID
        self.offset = offset
    }
}

public struct Bookmark: Identifiable, Codable, Sendable, Equatable {
    public let id: BookmarkID
    public var name: String
    public var anchor: BookmarkAnchor
    public var isAutoGenerated: Bool
    public var metadata: [String: String]

    public init(
        id: BookmarkID = BookmarkID(),
        name: String,
        anchor: BookmarkAnchor,
        isAutoGenerated: Bool = false,
        metadata: [String: String] = [:]
    ) {
        self.id = id
        self.name = name
        self.anchor = anchor
        self.isAutoGenerated = isAutoGenerated
        self.metadata = metadata
    }
}
