import Foundation
import Observation

public enum BookmarkMutation: Sendable, Equatable {
    case added(BookmarkID)
    case removed(BookmarkID)
    case updated(BookmarkID)
    case regenerated
}

public protocol BookmarkPositionResolver: Sendable {
    func pageNumber(for anchor: BookmarkAnchor) -> Int?
    func isAbove(anchor: BookmarkAnchor, relativeTo currentAnchor: BookmarkAnchor) -> Bool
}

@MainActor
@Observable
public final class BookmarkStore {
    public var bookmarks: [Bookmark]
    public var positionResolver: (any BookmarkPositionResolver)?

    private var observers: [UUID: @MainActor (BookmarkMutation) -> Void] = [:]

    public init(bookmarks: [Bookmark] = []) {
        self.bookmarks = bookmarks
    }

    public func add(_ bookmark: Bookmark) {
        bookmarks.append(bookmark)
        notify(.added(bookmark.id))
    }

    public func remove(_ id: BookmarkID) {
        bookmarks.removeAll { $0.id == id }
        notify(.removed(id))
    }

    public func update(_ id: BookmarkID, name: String? = nil, anchor: BookmarkAnchor? = nil) {
        guard let index = bookmarks.firstIndex(where: { $0.id == id }) else { return }
        if let name {
            bookmarks[index].name = name
        }
        if let anchor {
            bookmarks[index].anchor = anchor
        }
        notify(.updated(id))
    }

    public func bookmark(named name: String) -> Bookmark? {
        bookmarks.first { $0.name == name }
    }

    public func bookmark(for id: BookmarkID) -> Bookmark? {
        bookmarks.first { $0.id == id }
    }

    public func bookmark(forContentID contentID: String) -> Bookmark? {
        bookmarks.first { $0.anchor.contentID == contentID }
    }

    public var autoBookmarks: [Bookmark] {
        bookmarks.filter { $0.isAutoGenerated }
    }

    public var manualBookmarks: [Bookmark] {
        bookmarks.filter { !$0.isAutoGenerated }
    }

    public func regenerate(from items: [(name: String, contentID: String, metadata: [String: String])]) {
        bookmarks.removeAll { $0.isAutoGenerated }
        for item in items {
            bookmarks.append(
                Bookmark(
                    name: item.name,
                    anchor: BookmarkAnchor(contentID: item.contentID),
                    isAutoGenerated: true,
                    metadata: item.metadata
                )
            )
        }
        notify(.regenerated)
    }

    public func resolve(_ ref: CrossReference, from currentAnchor: BookmarkAnchor? = nil) -> ResolvedReference {
        guard let target = bookmark(for: ref.targetBookmarkID) else {
            return ResolvedReference(bookmarkName: "", displayText: "[broken reference]", isValid: false)
        }

        let displayText: String
        switch ref.displayStyle {
        case .title:
            displayText = target.name
        case .pageNumber:
            if let page = positionResolver?.pageNumber(for: target.anchor) {
                displayText = "page \(page)"
            } else {
                displayText = target.name
            }
        case .numberAndTitle:
            if let number = target.metadata["number"] {
                displayText = "\(number) \(target.name)"
            } else {
                displayText = target.name
            }
        case .aboveBelow:
            if let currentAnchor, let positionResolver {
                displayText = positionResolver.isAbove(anchor: target.anchor, relativeTo: currentAnchor) ? "above" : "below"
            } else {
                displayText = target.name
            }
        }

        return ResolvedReference(bookmarkName: target.name, displayText: displayText, isValid: true)
    }

    public func addObserver(_ observer: @escaping @MainActor (BookmarkMutation) -> Void) -> UUID {
        let id = UUID()
        observers[id] = observer
        return id
    }

    public func removeObserver(_ id: UUID) {
        observers.removeValue(forKey: id)
    }

    private func notify(_ mutation: BookmarkMutation) {
        for observer in observers.values {
            observer(mutation)
        }
    }
}
